stages:
  - build
  - test
  - deploy

.default-pipelines: &default-pipelines
  only:
    - master
    - tags
    - merge_requests

drupal_codequality:
  <<: *default-pipelines
  image: hussainweb/drupalqa:php7.4
  stage: test
  script:
    - phpcs --standard=phpcs.xml.dist --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ {_docroot_}/modules/custom
    - phpmd {_docroot_}/modules/custom/ text phpmd.xml
  tags:
    - docker
  except:
    - schedule

drupal_tests:
  <<: *default-pipelines
  image: hussainweb/drupal-base:php7.4
  services:
    - name: bitnami/mariadb:10.4
      alias: mariadb
  stage: test
  tags:
    - docker
  variables:
    SITE_BASE_URL: 'http://localhost'
    ALLOW_EMPTY_PASSWORD: "yes"

  before_script:
    - ./.gitlab/ci.sh

  script:
    - composer install -o

    # Clearing drush cache and importing configs
    - ./vendor/drush/drush/drush cr
    - ./vendor/drush/drush/drush -y updatedb
    - ./vendor/drush/drush/drush -y config-import

    # Run PHPUnit tests
    - ./vendor/bin/phpunit --testsuite unit
    - ./vendor/bin/phpunit --bootstrap=./vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php --configuration ./phpunit.xml --testsuite existing-site
  except:
    - schedule
